src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * 
 * 
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Firstname;
    
    /**
     * @ORM\Column(type="string", length=10)
     */
    private $Username;

     /**
     * @ORM\Column(type="string", length=225)
     * 
     * 
     *  
     */
    private $Email;

    /**
     * 
     * 
     * @ORM\Column(type="string", length=255)
     */
    private $Password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $resetToken;
     /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;
      /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\GroupT", mappedBy="users")
     */
    private $groupTs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Repo", mappedBy="userId", cascade="persist")
     */
    private $repos;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $userimage;

    /**
     * @ORM\OneToMany(targetEntity=Messageholder::class, mappedBy="SentBy", cascade="remove")
     */
    private $usersent;

    
    public function __construct()
    {
        $this->groupTs = new ArrayCollection();
        $this->repos = new ArrayCollection();
        $this->usersent = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }
    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }
    public function getEmail(): ?string
    {
        return $this->Email;
    }
    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }
    public function getResetToken(): string
    {
        return $this->resetToken;
    }
    public function setResetToken(?string $resetToken): void
    {
        $this->resetToken = $resetToken;
    }

    public function getSalt(){
        return null;
    }
    public function eraseCredentials(){
        return null;
    }

    /**
     * @return Collection|GroupT[]
     */
    public function getGroupTs(): Collection
    {
        return $this->groupTs;
    }

    public function addGroupT(GroupT $groupT): self
    {
        if (!$this->groupTs->contains($groupT)) {
            $this->groupTs[] = $groupT;
            $groupT->addUser($this);
        }

        return $this;
    }

    public function removeGroupT(GroupT $groupT): self
    {
        if ($this->groupTs->contains($groupT)) {
            $this->groupTs->removeElement($groupT);
            $groupT->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Repo[]
     */
    public function getRepos(): Collection
    {
        return $this->repos;
    }

    public function addRepo(Repo $repo): self
    {
        if (!$this->repos->contains($repo)) {
            $this->repos[] = $repo;
            $repo->setUserId($this);
        }

        return $this;
    }

    public function removeRepo(Repo $repo): self
    {
        if ($this->repos->contains($repo)) {
            $this->repos->removeElement($repo);
            // set the owning side to null (unless already changed)
            if ($repo->getVisibility() === $this) {
                $repo->setVisibility(false);
            }
        }

        return $this;
    }

   /** Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */

    public function getRoles()
    {
      //  $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
       // $roles[] = 'ROLE_USER';

        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
       public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUserimage(): ?string
    {
        return $this->userimage;
    }

    public function setUserimage(?string $userimage): self
    {
        $this->userimage = $userimage;

        return $this;
    }

    /**
     * @return Collection|Messageholder[]
     */
    public function getUsersent(): Collection
    {
        return $this->usersent;
    }

    public function addUsersent(Messageholder $usersent): self
    {
        if (!$this->usersent->contains($usersent)) {
            $this->usersent[] = $usersent;
            $usersent->setSentBy($this);
        }

        return $this;
    }

    public function removeUsersent(Messageholder $usersent): self
    {
        if ($this->usersent->removeElement($usersent)) {
            // set the owning side to null (unless already changed)
            if ($usersent->getSentBy() === $this) {
                $usersent->setSentBy(null);
            }
        }

        return $this;
    }

    
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\RepoFormType;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use App\Service\RepoService;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use App\Entity\User;
use App\Entity\GroupT;
use App\Entity\repo;
use App\Entity\Messageholder;
use Knp\Component\Pager\PaginatorInterface;

class ProfileController extends AbstractController
{
    private $repositoryService;
    private $paginator;

    public function __construct(RepoService $repositoryService, PaginatorInterface $paginator){
        $this->repositoryService = $repositoryService;
        $this->paginator = $paginator;
    }
    /**
     * @Route("/profile", name="profile")
     */
     public function index(): Response
    {
     $user=$this->getUser();
       if($user != null){
       $joining =$this->getDoctrine()->getRepository(User::class)->findBy(['title'=>'user']);
       $privilege =$this->getDoctrine()->getRepository(User::class)->findBy(['title'=>'administrator']);
       $group =$this->getDoctrine()->getRepository(GroupT::class)->findAll();
       $publicrepo =$this->getDoctrine()->getRepository(Repo::class)->findBy(['visibility'=>'public']);
       $privaterepo =$this->getDoctrine()->getRepository(Repo::class)->findBy(['visibility'=>'private']);
        return $this->render('profile/index.html.twig', ['controller_name' => 'ProfileController',
       'join'=>$joining,'privilege'=>$privilege,'group'=>$group,'public'=>$publicrepo,'private'=>$privaterepo]);
        }
       else{
        return $this->redirectToRoute('app_login');
       }
    }
      /**
     * @Route("/profile/admin", name="admin")
     */
    public function uadmin(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
     $user=$this->getUser();
       if($user != null){
       $joining =$this->getDoctrine()->getRepository(User::class)->findBy(['title'=>'administrator']);
        $em = $this->getDoctrine()->getManager();
        $connection=$em->getConnection();
        $statement=$connection->prepare("select username from user where username='".$request->request->get('username')."'");
        $statement2=$connection->prepare("select email from user where email='".$request->request->get('email')."'");
        $statement->execute();
        $statement2->execute();
        $verify=$statement->fetchAll();
        $verifyemail=$statement2->fetchAll();
        $cpass="ubucket";
        if ($request->isMethod('POST')) {
            if(!$verify){
                if(!$verifyemail){
            $user = new User();
            $user->setFirstname($request->request->get('fname'));
            $user->setUsername($request->request->get('uname'));
            $user->setEmail($request->request->get('email'));
            $user->setTitle('administrator');
            $user->setRoles([
                            "ROLE_ADMIN"
                            ]);
            $user->setPassword($passwordEncoder->encodePassword(
                $user,
                $cpass
            ));

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute("admin");
        }
        else
        {
            $this->addFlash('username',  'This email  '.$request->request->get('email').' already exists!');
            return $this->render('profile/adminusers.html.twig',['display'=>$joining]);
         }
        }
        else
        {
            $this->addFlash('username',  'This username '.$request->request->get('uname').' already exists!');
           return $this->render('profile/adminusers.html.twig',['display'=>$joining]);
        }

        }
        return $this->render('profile/adminusers.html.twig',['display'=>$joining]);
        }
       else{
        return $this->redirectToRoute('app_login');
       }
    }
     /**
     * @Route("/profile/joining/user/list", name="joining")
     */
    public function ujoining(): Response
    {
     $user=$this->getUser();
       if($user != null){
       $joining =$this->getDoctrine()->getRepository(User::class)->findBy(['title'=>'user']);
        return $this->render('profile/joinusers.html.twig',['display'=>$joining]);
        }
       else{
        return $this->redirectToRoute('app_login');
       }
    }

/**
     * @Route("/profile/remove/user", name="removeuser")
     */
    public function removeadmin(Request $request): Response
    {

            $user1=$this->getUser();
            $em=$this->getDoctrine()->getManager();
            $userid=$user1->getId();
            $parametersToValidate = $request->query->all();
            $parametersToValidate=array_values($parametersToValidate);
            $name = $parametersToValidate[0];
            $projectuser =$this->getDoctrine()->getRepository(User::class)->findOneBy(['Username' => $name]);
            $id=$projectuser->getId();
            $enter =$this->getDoctrine()->getRepository(Repo::class)->findOneBy(['userId' => $id]);
            $message =$this->getDoctrine()->getRepository(Messageholder::class)->findOneBy(['SentBy' => $id]);
            $enter1 =$this->getDoctrine()->getRepository(User::class)->findOneBy(['title' => 'superadmin']);

            if($projectuser){

                    $title = $projectuser->getTitle();
                    if($title == 'administrator' or $title == 'superadmin'){
                      if($enter){
                       $enter->setUserId($enter1);
                       $enter->setVisibility(true);
                       }
                       if($message)
                       {
                       $projectuser->removeUsersent($message);
                       }
                       $em->remove($projectuser);
                       $em->flush();
                       return $this->redirectToRoute('admin');
                    }
                    else{
                      if($enter){
                       $enter->setUserId($enter1);
                       $enter->setVisibility(true);
                       }
                      if($message)
                       {
                       $projectuser->removeUsersent($message);
                       }
                      $em->remove($projectuser);
                      $em->flush();
                      return $this->redirectToRoute('joining');
                    }

            }
            else if($user1){
                   if($enter){
                       $enter->setUserId($enter1);
                       $enter->setVisibility(true);
                     }
                      if($message)
                       {
                       $projectuser->removeUsersent($message);
                       }
                    $em->remove($projectuser);
                    $em->flush();
                    $success="Your account no longer exists contact administrator for more info";
                    $session = $this->get('session');
                    $session = new Session();
                    $session->invalidate();
                    return new response($success);

            }
            else{
                    return new response("failed to remove user");
                 }


    }
         /**
     * @Route("/profile/admin/revoke/privilege/manager", name="revoke")
     */
    public function revoke(Request $request): Response
    {
     $user=$this->getUser();
       if($user != null){
        $parametersToValidate = $request->query->all();
        $parametersToValidate=array_values($parametersToValidate);
        $name = $parametersToValidate[0];
        $joining =$this->getDoctrine()->getRepository(User::class)->findOneBy(['Username'=>$name]);
        $joining->setRoles(
                ['ROLE_USER']
        );
        $joining->setTitle('user');
        $em = $this->getDoctrine()->getManager();
        $em->persist($joining);
        $em->flush();
        return $this->redirectToRoute('admin');
        }
       else{
        return $this->redirectToRoute('app_login');
       }
    }
     /**
     * @Route("/profile/repository/available/list", name="repos")
     */
    public function urepo(Request $request): Response
    {
     $user=$this->getUser();
       if($user != null){
        $repo = new Repo();
        $form = $this->createform(RepoFormType::class,$repo);
        $form->handleRequest($request);
       $joining =$this->getDoctrine()->getRepository(Repo::class)->findAll();
        $em = $this->getDoctrine()->getManager();
        $connection=$em->getConnection();
        $statement2=$connection->prepare("
         SELECT repo.id,username FROM
          `user` inner join repo on repo.user_id_id=user.id");
        $statement2->execute();
        $verify=$statement2->fetchAll();
         if ($form->isSubmitted() && $form->isValid()) {

            $result = $this->repositoryService->create($user, $repo);

            if ($result) {
                return $this->redirectToRoute('repos');
            }

        }
        return $this->render('profile/repositories.html.twig',['display'=>$joining,

templates/profile/adminusers.html.twig
{% extends 'userbase.html.twig' %}
{% block body %}
{% if app.user %}
  {% include('profile/usermenu.html.twig') %}

  <div class="page-wrapper mdc-toolbar-fixed-adjust">
      <main class="content-wrapper">
      <!-- start -->
        <div class="mdc-layout-grid">
          <div class="mdc-layout-grid__inner">
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
              <div class="mdc-card">
                <div class="mdc-layout-grid__inner">
                  <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-9">
                    <section class="purchase__card_section">
                      <p class="text-red font-weight-bold"><span class="badge bg-danger mr-1">{{ display|length }}</span> Privilege Users</p>
                    </section>
                  </div>
                   <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3">
                          <section class="purchase__card_section">
                                   <a href="#" class="btn btn-primary text-lowercase" data-bs-toggle="modal" data-bs-target="#Form">
                                       Add
                                    </a>
                           </section>
                           <!---START TEST--->
                        <div class="modal fade" id="Form" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" >
                         <div class="modal-dialog modal-md" >
                           <div class="modal-content" >
                             <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel" style="padding-left:40%;">Add Privilege User</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                           </div>
                          <div class="modal-body" >
                           <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                                    <div class="mdc-card">
                                      <section class="mdc-card__supporting-text">
                                               <!-- form start -->
                                        <form  action="" method="post" class="mt-5">
                                             <div class="mdc-layout-grid__inner">
                                                      <!-- Name area-->
                                                 <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
                                                     <div class="template-demo">
                                                        <div id="demo-tf-box-leading-wrapper">
                                                           <div id="tf-box-leading-test" class="mdc-text-field mdc-text-field--box mdc-text-field--with-leading-icon w-100">
                                                               <input required pattern=".{2,}" type="text" placeholder="Enter Full Name" name="fname"  class="mdc-text-field__input text-lowercase">
                                                            <div class="mdc-text-field__bottom-line"></div>
                                                         </div>
                                                     </div>
                                                   </div>
                                                 </div>
                                                         <!-- Name area-->
                                                 <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
                                                     <div class="template-demo">
                                                        <div id="demo-tf-box-leading-wrapper">
                                                           <div id="tf-box-leading-test" class="mdc-text-field mdc-text-field--box mdc-text-field--with-leading-icon w-100">
                                                               <input required pattern=".{2,}" type="text" placeholder="Enter Username" name="uname"  class="mdc-text-field__input text-lowercase">
                                                            <div class="mdc-text-field__bottom-line"></div>
                                                         </div>
                                                     </div>
                                                   </div>
                                                 </div>
                                                         <!-- Name area-->
                                                 <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-12-desktop">
                                                     <div class="template-demo">
                                                        <div id="demo-tf-box-leading-wrapper">
                                                           <div id="tf-box-leading-test" class="mdc-text-field mdc-text-field--box mdc-text-field--with-leading-icon w-100">
                                                               <input required pattern=".{5,@}" type="email" placeholder="Enter email" name="email"  class="mdc-text-field__input text-lowercase">
                                                            <div class="mdc-text-field__bottom-line"></div>
                                                         </div>
                                                     </div>
                                                   </div>
                                                 </div>
                                                  <!-- message action -->
                                             <div class="mdc-layout-grid__cell  mdc-layout-grid__cell--span-12-desktop">
                                                  <p class="align-item-center">
                                                      <i class="material-icons mdc-theme--secondary icon-md">SN</i>
                                                       <span class="mdc-card__title mdc-card__title--middle text-lowercase text-center">
                                                       Default password for privilege user is ubucket </span>
                                                  </p>
                                             </div>
                                            <!-- end message action -->
                                           <!-- submit action -->
                                              <div class="mdc-layout-grid__cell  mdc-layout-grid__cell--span-7-desktop">
                                               <p class="align-item-center">
                                                 <button type="submit" class="btn btn-primary text-lowercase mb-0">
                                                      Add
                                                 </button>
                                               </p>
                                              </div>
                                           <!-- end submit action -->
                                        </form>
                                      </section>
                                    </div>
                           </div>
                          </div>
                   </div>
                </div>
              </div>
           <!--END TEST-->
           </div>
        </div>
      </div>
  </div>
   <!--end-->


            <!--start table-->
           <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
              <div class="mdc-card table-responsive" style="overflow-x:auto;">
                <div class="card text-primary font-weight-bold" style="overflow-x:auto;">
                    <p class="text-red" id="name-validation-msg">
                             {% for messages in app.flashes('username') %}
                                    {{ messages}}
                             {% endfor %}
                     </p>
                 <div class="card-body">

                    <table id="zero_config" class="table table-striped" style="width:100%">
                      <thead >
                        <tr >
                          <th>#</th>
                          <th class="text-left">Name</th>
                          <th class="text-left">Username</th>
                          <th class="text-left">Email</th>
                           <th class="text-center">Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                       {% for temp,show in display %}
                            <tr>
                              <td>{{ temp +1 }}</td>
                              <td class="text-left">{{ show.firstname }}</td>
                              <td class="text-left">{{ show.username }}</td>
                              <td class="text-left">{{ show.email}}</td>
                              <td >
                               <a href="{{ path('removeuser', { 'user' : show.username }) }}" class="col btn btn-md btn-danger text-white text-lowercase mb-0" data-mdc-auto-init="MDCRipple">Remove user</a>
                               <a href="{{ path('revoke', { 'user' : show.username }) }}" class="col btn btn-md btn-secondary text-white text-lowercase mb-0" data-mdc-auto-init="MDCRipple">Revoke privilege</a>
                             </td>
                            </tr>
                       {% endfor %}
                        </tbody>
                      </table>
                      </div>
                 </div>
              </div>
            </div>
            <!--end table -->
      </main>
</div>
<script>
 $(document).ready(function() {
    $('#zero_config').DataTable( {
        responsive: {
            details: {
                display: $.fn.dataTable.Responsive.display.modal( {
                    header: function ( row ) {
                        var data = row.data();
                        return 'Details for '+data[0]+' '+data[1];
                    }
                } ),
                renderer: $.fn.dataTable.Responsive.renderer.tableAll( {
                    tableClass: 'table'
                } )
            }
        }
    } );
} );



 </script>

{% endif %}

{% endblock %}

templates/profile/joinusers.html.twig
{% extends 'userbase.html.twig' %}
{% block body %}
{% if app.user %}
  {% include('profile/usermenu.html.twig') %}

  <div class="page-wrapper mdc-toolbar-fixed-adjust">
      <main class="content-wrapper">
      <!-- start -->
        <div class="mdc-layout-grid">
          <div class="mdc-layout-grid__inner">
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
              <div class="mdc-card">
                <div class="mdc-layout-grid__inner">
                  <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-9">
                    <section class="purchase__card_section">
                      <p class="text-red font-weight-bold"><span class="badge bg-danger mr-1">{{ display|length }}</span> Joining Users</p>
                    </section>
                  </div>
                </div>
              </div>
            </div>
            <!--end-->

            <!--start table-->
           <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
              <div class="mdc-card table-responsive" style="overflow-x:auto;">
                <div class="card text-primary font-weight-bold" style="overflow-x:auto;">
                 <div class="card-body">
                    <table id="zero_config" class="table table-striped" style="width:100%">
                      <thead >
                        <tr >
                          <th>#</th>
                          <th class="text-left">Name</th>
                          <th class="text-left" >Username</th>
                          <th class="text-left">Email</th>
                           <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                       {% for temp,show in display %}
                            <tr>
                              <td>{{ temp +1 }}</td>
                              <td class="text-left">{{ show.firstname }}</td>
                              <td class="text-left">{{ show.username }}</td>
                              <td class="text-left">{{ show.email}}</td>
                              <td>
                               <a href="{{ path('removeuser', { 'user' : show.username }) }}" class="col btn btn-md btn-danger text-lowercase mb-0" data-mdc-auto-init="MDCRipple">Remove User</a>
                             </td>
                            </tr>
                       {% endfor %}
                        </tbody>
                      </table>
                      </div>
                 </div>
              </div>
            </div>
            <!--end table -->
      </main>
</div>
  <script>
 $(document).ready(function() {
    $('#zero_config').DataTable( {
        responsive: {
            details: {
                display: $.fn.dataTable.Responsive.display.modal( {
                    header: function ( row ) {
                        var data = row.data();
                        return 'Details for '+data[0]+' '+data[1];
                    }
                } ),
                renderer: $.fn.dataTable.Responsive.renderer.tableAll( {
                    tableClass: 'table'
                } )
            }
        }
    } );
} );



 </script>

{% endif %}

{% endblock %}