src/Entity/Repo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="repo")
 * @ORM\Entity(repositoryClass="App\Repository\RepoRepository")
 */
class Repo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visibility;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="repos", fetch="EAGER")
     */
    private $userId;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\GroupT", inversedBy="repos")
     * 
     */
    private $groupId;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getVisibility(): ?bool
    {
        return $this->visibility;
    }

    public function setVisibility(bool $visibility): self
    {
        $this->visibility = $visibility;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->userId;
    }

    public function setUserId(?User $userId): self
    {
        $this->userId = $userId;

        return $this;
    }

    public function getGroupId(): ?GroupT
    {
        return $this->groupId;
    }

    public function setGroupId(?GroupT $groupId): self
    {
        $this->groupId = $groupId;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * 
 * 
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Firstname;
    
    /**
     * @ORM\Column(type="string", length=10)
     */
    private $Username;

     /**
     * @ORM\Column(type="string", length=225)
     * 
     * 
     *  
     */
    private $Email;

    /**
     * 
     * 
     * @ORM\Column(type="string", length=255)
     */
    private $Password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $resetToken;
     /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;
      /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\GroupT", mappedBy="users")
     */
    private $groupTs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Repo", mappedBy="userId", cascade="persist")
     */
    private $repos;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $userimage;

    /**
     * @ORM\OneToMany(targetEntity=Messageholder::class, mappedBy="SentBy", cascade="remove")
     */
    private $usersent;

    
    public function __construct()
    {
        $this->groupTs = new ArrayCollection();
        $this->repos = new ArrayCollection();
        $this->usersent = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }
    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }
    public function getEmail(): ?string
    {
        return $this->Email;
    }
    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }
    public function getResetToken(): string
    {
        return $this->resetToken;
    }
    public function setResetToken(?string $resetToken): void
    {
        $this->resetToken = $resetToken;
    }

    public function getSalt(){
        return null;
    }
    public function eraseCredentials(){
        return null;
    }

    /**
     * @return Collection|GroupT[]
     */
    public function getGroupTs(): Collection
    {
        return $this->groupTs;
    }

    public function addGroupT(GroupT $groupT): self
    {
        if (!$this->groupTs->contains($groupT)) {
            $this->groupTs[] = $groupT;
            $groupT->addUser($this);
        }

        return $this;
    }

    public function removeGroupT(GroupT $groupT): self
    {
        if ($this->groupTs->contains($groupT)) {
            $this->groupTs->removeElement($groupT);
            $groupT->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Repo[]
     */
    public function getRepos(): Collection
    {
        return $this->repos;
    }

    public function addRepo(Repo $repo): self
    {
        if (!$this->repos->contains($repo)) {
            $this->repos[] = $repo;
            $repo->setUserId($this);
        }

        return $this;
    }

    public function removeRepo(Repo $repo): self
    {
        if ($this->repos->contains($repo)) {
            $this->repos->removeElement($repo);
            // set the owning side to null (unless already changed)
            if ($repo->getVisibility() === $this) {
                $repo->setVisibility(false);
            }
        }

        return $this;
    }

   /** Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */

    public function getRoles()
    {
      //  $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
       // $roles[] = 'ROLE_USER';

        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
       public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUserimage(): ?string
    {
        return $this->userimage;
    }

    public function setUserimage(?string $userimage): self
    {
        $this->userimage = $userimage;

        return $this;
    }

    /**
     * @return Collection|Messageholder[]
     */
    public function getUsersent(): Collection
    {
        return $this->usersent;
    }

    public function addUsersent(Messageholder $usersent): self
    {
        if (!$this->usersent->contains($usersent)) {
            $this->usersent[] = $usersent;
            $usersent->setSentBy($this);
        }

        return $this;
    }

    public function removeUsersent(Messageholder $usersent): self
    {
        if ($this->usersent->removeElement($usersent)) {
            // set the owning side to null (unless already changed)
            if ($usersent->getSentBy() === $this) {
                $usersent->setSentBy(null);
            }
        }

        return $this;
    }

    
}

src/Controller/RepoController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use GitStash\Exception\ReferenceNotFoundException;
use App\Entity\Repo;
use App\Form\RepoFormType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\User;
use App\Repository\RepoRepository;
use App\Repository\UserRepository;
use App\Repository\GroupTRepository;
use App\Service\GitServiceFactory;
use App\DataObject\DataObjectFactory;
use Knp\Component\Pager\PaginatorInterface;


class RepoController extends AbstractController
{
    private $gitservice;
    private $repoRepository;
    private $userRepository;
    private $groupTRepository;
    private $appdataobjectFactory;
    private $paginator;

    public function __construct(GitServiceFactory $gitService,GroupTRepository $groupTRepository,RepoRepository $repoRepository, DataObjectFactory $appdataobjectFactory, PaginatorInterface $paginator, UserRepository $userRepository){
        $this->gitservice = $gitService;
        $this->repoRepository = $repoRepository;
        $this->groupTRepository = $groupTRepository;
        $this->appdataobjectFactory = $appdataobjectFactory;
        $this->paginator = $paginator;
        $this->userRepository = $userRepository;
    }

    /**
     * @Route("/repo", name="repo")
     * 
     */
    public function indexAction(Request $request)
    {
    
        $parametersToValidate = $request->query->all();
        $parametersToValidate=array_values($parametersToValidate);
        $name = $parametersToValidate[1];
        $user = $parametersToValidate[0];
        $repo = $this->repoRepository->findOneBy(['name' => $name]);
        $user = $this->userRepository->findOneBy(['Username' => $user]);
        $gitService = $this->gitservice->create($repo);
        return $this->render('repo/index.html.twig', array(
            'repo' => $repo,
            'git' => $gitService,
            'user'=>$user
        ));
    }
    
    /**
     * @Route("/repository/{id}/{repo}", name="repository")
     * 
     */
    public function searchResult(Request $request,$id,$repo)
    {
    
        $parametersToValidate = $request->query->all();
        $parametersToValidate=array_values($parametersToValidate);
        // $name = $parametersToValidate[1];
        // $username = $parametersToValidate[0];
        $user = $this->userRepository->findOneBy(['Username' => $id]);
        $repo = $this->repoRepository->findOneBy(['name' => $repo]);
        $me = $repo;
        $gitService = $this->gitservice->create($repo);
        return $this->render('searchpage/index.html.twig', array(
            'repo' => $repo,
            'git' => $gitService,
            'username' =>$id,
            'user' => $user,
        ));
    }
  /**
     * @Route("/repogt/{id}/{grp}/{reponame}", name="repogt")
     * 
     */
    public function Action(Request $request,$id,$grp,$reponame)
    {
    
        $parametersToValidate = $request->query->all();
        $parametersToValidate=array_values($parametersToValidate);
        //$name = $parametersToValidate[1];

        $repo = $this->repoRepository->findOneBy(['id' => $reponame]);
        $name = $repo->getName();
        $group4 = $this->groupTRepository->findOneBy(['id' => $grp]);
        $report = new Repo();
        $form = $this->createform(RepoFormType::class,$report);
         $form->handleRequest($request);
           if ($form->isSubmitted() && $form->isValid()) {

            $result = $this->repositoryService->createGroupRepos($user,$group4,$report);

            if ($result) {
                return $this->redirect($this->generateUrl('repogt', array('id'=>$id,'grp'=>$grp,'group' => $group4->getName(), 'reponame' => $report->getName(),'git'=>$gitService)));
            }


        }
        $gitService = $this->gitservice->create($repo);
        return $this->render('group/groupbranch.html.twig', array(
            'repo' => $repo,
            'name' => $name,
            'group' => $id,
            'group4' => $group4,
            'grp' => $grp,
            'git' => $gitService,
            'repo_form' => $form->createView(),
        ));
    }


    /**
     * Displays contributors
     *
     * @Route("/contributors", name="repo_contributors")
     */
    public function contributorsAction(Request $request)
    {
	$parametersToValidate = $request->query->all();
        $parametersToValidate=array_values($parametersToValidate);
        $name = $parametersToValidate[1];
        $repo = $this->repoRepository->findOneBy(['name' => $name]);
        $username = $parametersToValidate[0];
  
        $user = $this->userRepository->findOneBy(['Username' => $username]);

        $gitService = $this->gitservice->create($repo);

        $repoObject = $this->appdataobjectFactory->create($repo);
        $totalContributors = count($repoObject->getContributors());
        $contributors = array_slice($repoObject->getContributors(), 0, 24);

        return $this->render('repo/contributors.html.twig', array(
            'position' => 0,
            'total_contributors' => $totalContributors,
            'repo' => $repoObject,
            'contributors' => $contributors,
            'git' => $gitService,
            'user'=> $user,
        ));
    }

    /**
     * Displays contributors
     *
     * @Route("/contributors", name="repo_contributors_ajax")
     * 
     */
    public function contributorsAjaxAction(Request $request, Repo $repo, $offset)
    {
        $gitService = $this->gitservice->create($repo);

        $repoObject = $this->get('app.data_object_factory')->create($repo);
        $totalContributors = count($repoObject->getContributors());
        $contributors = array_slice($repoObject->getContributors(), $offset, 24);

        return $this->render('repo/fragments/contributors.html.twig', array(
            'position' => $offset,
            'total_contributors' => $totalContributors,
            'repo' => $repoObject,
            'contributors' => $contributors,
            'git' => $gitService,
        ));

    }


    /**
     * Display given blob in given tree
     *
     * @Route("/blob", name="repo_blob_view")
     * 
     */
    public function blobAction(Request $request)
    {
	  $parametersToValidate = $request->query->all();
          $parametersToValidate=array_values($parametersToValidate);
          $name = $parametersToValidate[1];
          $tree = $parametersToValidate[2];
          $path = $parametersToValidate[3];

          $username = $parametersToValidate[0];
  
          $user = $this->userRepository->findOneBy(['Username' => $username]);
  
          $repo = $this->repoRepository->findOneBy(['name' => $name]);
        if (! $this->TreePathExists($repo, $tree, $path)) {
            return $this->redirect($this->generateUrl('repo', array('user' => $repo->getOwner()->getUsername(), 'repo' => $repo->getName())));
        }

        $file = basename($path);
        $path = dirname($path);

        $vars = $this->getRepoVars($repo, $tree, $path);
        $vars['file'] = $file;
        $vars['user'] = $user;

        return $this->render('repo/blob.html.twig', $vars);
    }

    protected function treePathExists(Repo $repo, $tree, $path = null)
    {
        $gitService = $this->gitservice->create($repo);

        try {
            $gitService->refToSha($tree);
            $gitService->getTreeFromBranchPath($tree, $path);
        } catch (ReferenceNotFoundException $e) {
            return false;
        }

        return true;
    }

    protected function getRepoVars(Repo $repo, $tree, $path)
    {
        $gitService = $this->gitservice->create($repo);

        $branch = $tree; // Or this could be a tag
        $commit = $gitService->fetchCommitFromRef($tree);
        $tree = $gitService->getTreeFromBranchPath($tree, $path);


        $crumbtrail = array();

        if (strlen($path) > 0 && $path[0] == "/") {
            $path = substr($path, 1);
        }
        if ($path == "") {
            $pathArray = array("");
        } else {
            $pathArray = explode("/", $path);
        }
        array_unshift($pathArray, "");

        $p = array();
        foreach ($pathArray as $element) {
            $p[] = $element;
            $thisPath = join('/', $p);
            if ($element == "") {
                $element = "Root";
            }
            $crumbtrail[] = array(
                'name' => $element,
                'href' => $this->generateUrl('repo_tree', array(
                    'user' => $repo->getUserId()->getUsername(),
                    'repo' => $repo->getName(),
                    'tree' => $branch,
                    'path' => $thisPath,
                )),
            );
        }

        return array(
            'repo' => $this->appdataobjectFactory->create($repo),
            'git' => $gitService,
            'tree' => $tree,
            'commit' => $commit,
            'branch' => $branch,
            'crumbtrail' => $crumbtrail,
            'path' => $path,
        );
    }


    /**
      * Display specific tree based on branch/ref.
      *
      * @Route("/tree/{user}/{repo}/{tree}", name="repo_tree")
      *
      * 
      */
      public function treeAction(Request $request,$user, $repo, $tree)
      {
          $parametersToValidate = $request->query->all();
          $parametersToValidate=array_values($parametersToValidate);
        //   $name = $parametersToValidate[1];
        //   $tree = $parametersToValidate[2];
          $path = '/';
          $repo = $this->repoRepository->findOneBy(['name' => $repo]);
        //   $username = $parametersToValidate[0];
  
          $user = $this->userRepository->findOneBy(['Username' => $user]);
          if (! $this->treePathExists($repo, $tree, $path)) {

templates/repo/fragments/contributors.html.twig
{% for contributor_row in contributors|batch(4) %}
    <div class="row">
    {% for contributor in contributor_row %}
        <div class="col-xs-3 text-center">
            <div class="well-sm" style="background-color: #f8f8ff">
                {% set position = position + 1 %}
                <b>#{{ position }} {{ contributor.name }}</b><br>
                {{ contributor.email }}
                <img class="center-block img-responsive img-rounded" src="{{ gravatar(contributor.email) }}">
                <i class="fa fa-line-chart"></i> {{ contributor.count }} commits
            </div>
            <br>
        </div>
        {% endfor %}
    </div>
{% endfor %}

{% if position < total_contributors %}
<p class="text-center">
    <a href="{{ path('repo_contributors_ajax', { user: repo.owner.username, repo: repo.name, offset: position }) }}">Show more contributors...</a>
</p>
{% endif %}

templates/repo/fragments/header.html.twig
{% if app.user != null %}
 <div class="page-wrapper mdc-toolbar-fixed-adjust">
  <main class="content-wrapper" style="background:white;">
    <div class="mdc-layout-grid">
          <div class="mdc-layout-grid__inner">
          <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
           <div class="mdc-card">
                <div class="mdc-layout-grid__inner">
                  <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                    <section class="purchase__card_section">
                      <p>
                      <span class="text-uppercase font-weight-bold">Repo: <span class="text-red">{{ repo.name }} </span>
                      {% if repo.groupId %}&nbsp; Group:
                       <a href="{{ path("grprepos", {  id:repo.groupId.name,grp:repo.groupId.id}) }}" class="btn"><span class="text-red font-weight-bold"> {{repo.groupId.name}} </a>
                       {% endif %}
                       </span>
                      </p>
                        <p>
                      <span class="text-lowercase">{{ repo.description }}</span></span>
                      </p>
                    </section>
                  </div>
                </div>
           </div>
      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
        <div class="mdc-layout-grid">
          <div class="mdc-layout-grid__inner">
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
              <div class="mdc-card">
                <div class="mdc-layout-grid__inner">
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                 <section class="purchase__card_section">
                    <form class="form-inline">
                        <div class="form-group">
                            <label for="branch">Branch:</label>
                            <select id="branch_select" class="form-control input-sm">
                            {% for name, sha in git.branches %}

                                <option {% if name == branch %}selected{% endif %} data-href="{{ path('repo_tree', { 'user' : repo.userId.username, 'repo' : repo.name, 'tree' : name, 'path' : "/" }) }}">{{ name }}</option>
                            {% endfor %}
                            </select>
                            <button id="branch_submit" class="form-control btn btn-success btn-md input-sm">Go <i class="mdi mdi-8px mdi-play"></i></button>
                        </div>
                       </form>
                    </section>
                   </div>
                   </div>
                </div>
              </div>
    </div>
    </div>
    </div>
    </div>
<div class="col-sm-4">
{% if git.tags|length %}
        <form class="form-inline">
            <div class="form-group">
                <label for="tag">Tag:</label>
                <select id="tag_select" class="input-sm form-control">
                {% for name, sha in git.tags %}
                    <option {% if name == branch %}selected{% endif %} data-href="{{ path('repo_tree', { 'user' : repo.userId.username, 'repo' : repo.name, 'tree' : name, 'path' : "/" }) }}">{{ name }}</option>
                {% endfor %}
                </select>
                <button id="tag_submit" class="form-control btn btn-success btn-xs input-sm">Go <i class="mdi mdi-8px mdi-play"></i></button>
            </div>
        </form>
{% endif %}
    </div>
    {# <div class="col-sm-4">
        <a href="#" class="pull-right btn btn-info btn-sm"><i class="fa fa-balance-scale"></i> License</a>
    </div> #}
</div>

<div class="row well-sm">
    <div class="col-xs-12">
        <ul class="breadcrumb">
          Path:
{% for element in crumbtrail %}
          <li {% if loop.last %}class="active"{% endif %}><a href="{{ element.href }}" class="btn">{{ element.name }}</a></li>
{% endfor %}
        </ul>
    </div>
    <div class="col-xs-12">
        <table class="table table-condensed">
            <tr>
                <td><a href="{{ path('commits_log', { 'user' : repo.userId.username, 'repo' : repo.name, 'tree' : branch, 'path' : "/" }) }}" class="btn text-primary font-weight-bold"><i class="mdi mdi-24px mdi-chart-line-variant" style="color:lightgrey;"></i> commits <span class="badge bg-danger">{{ repo.totalCommits }}</span> </td>
                <td> <a href="{{ path('repo_contributors', { user: repo.userId.username, repo: repo.name, 'branch' : branch }) }}" class="btn text-primary font-weight-bold"><i class="mdi mdi-24px  mdi-account" style="color:lightgrey;"></i> contributors <span class="badge bg-danger">{{ repo.contributors | length }}</span> </a></td>
                <td><a href="{{ path('tree_graph', { 'user' : repo.userId.username, 'repo' : repo.name, 'tree' : branch, 'path' : "/" }) }}" class="btn text-primary font-weight-bold"> <i class="mdi mdi-24px mdi-eye" style="color:lightgrey;"></i> Graph</a></td>
                <td><a href="{{ path('stats', { user: repo.userId.username, repo: repo.name, 'branc' : branch, 'path' : "/" }) }}" class="btn text-primary font-weight-bold"><i class="mdi mdi-24px mdi-star" style="color:lightgrey;"></i> stats</a></td>
            </tr>
        </table>
    </div>
</div>


{% else %}
   <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-8">
           <div class="mdc-card">
              <div class="mdc-layout-grid__inner">
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-8">
                    <section class="purchase__card_section">
                      <p>
                      <span class="text-uppercase font-weight-bold">Repo: <span class="text-red">{{ repo.name }} </span>
                      {% if repo.groupId %}&nbsp; Group:
                       <a href="{{ path("grprepos", {  id:repo.groupId.name,grp:repo.groupId.id}) }}" class="btn"><span class="text-red font-weight-bold"> {{repo.groupId.name}} </a>
                       {% endif %}
                       </span>
                      </p>
                        <p>
                      <span class="text-lowercase">{{ repo.description }}</span>
                      </p>
                    </section>
                </div>
              </div>
           </div>
   </div>
    <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
        <div class="mdc-card">
           <div class="mdc-layout-grid__inner">
             <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-8">
              <section class="purchase__card_section">
                    <form class="form-inline">
                        <div class="form-group">
                            <label for="branch">Branch:</label>
                            <select id="branch_select" class="form-control input-sm">
                            {% for name, sha in git.branches %}

                                <option {% if name == branch %}selected{% endif %} data-href="{{ path('repo_tree', { 'user' : repo.userId.username, 'repo' : repo.name, 'tree' : name, 'path' : "/" }) }}">{{ name }}</option>
                            {% endfor %}
                            </select>
                            <button id="branch_submit" class="form-control btn btn-success btn-md input-sm">Go <i class="mdi mdi-8px mdi-play"></i></button>
                        </div>
                       </form>
              </section>
              </div>
           </div>
        </div>
    </div>

    <div class="col-sm-4">
{% if git.tags|length %}
        <form class="form-inline">
            <div class="form-group">
                <label for="tag">Tag:</label>
                <select id="tag_select" class="input-sm form-control">
                {% for name, sha in git.tags %}
                    <option {% if name == branch %}selected{% endif %} data-href="{{ path('repo_tree', { 'user' : repo.userId.username, 'repo' : repo.name, 'tree' : name, 'path' : "/" }) }}">{{ name }}</option>
                {% endfor %}
                </select>
                <button id="tag_submit" class="form-control btn btn-success btn-xs input-sm">Go <i class="mdi mdi-8px mdi-play"></i></button>
            </div>
        </form>
{% endif %}
    </div>
    {# <div class="col-sm-4">
        <a href="#" class="pull-right btn btn-info btn-sm"><i class="fa fa-balance-scale"></i> License</a>
    </div> #}
</div>

<div class="row well-sm">
    <div class="col-xs-12">
        <ul class="breadcrumb">
          Path:
{% for element in crumbtrail %}
          <li {% if loop.last %}class="active"{% endif %}><a href="{{ element.href }}">{{ element.name }}</a></li>
{% endfor %}
        </ul>
    </div>
    <div class="col-xs-12">
        <table class="table table-condensed">
            <tr>
                <td><a href="{{ path('commits_log', { 'user' : repo.userId.username, 'repo' : repo.name, 'tree' : branch, 'path' : "/" }) }}" class="btn text-primary font-weight-bold"><i class="mdi mdi-24px mdi-chart-line-variant" style="color:lightgrey;"></i> commits <span class="badge bg-danger">{{ repo.totalCommits }}</span> </td>
                <td> <a href="{{ path('repo_contributors', { user: repo.userId.username, repo: repo.name, 'branch' : branch }) }}" class="btn text-primary font-weight-bold"><i class="mdi mdi-24px  mdi-account" style="color:lightgrey;"></i> contributors <span class="badge bg-danger">{{ repo.contributors | length }}</span> </a></td>
                <td><a href="{{ path('tree_graph', { 'user' : repo.userId.username, 'repo' : repo.name, 'tree' : branch, 'path' : "/" }) }}" class="btn text-primary font-weight-bold"> <i class="mdi mdi-24px mdi-eye" style="color:lightgrey;"></i> Graph</a></td>
                <td><a href="{{ path('stats', { user: repo.userId.username, repo: repo.name, 'branc' : branch, 'path' : "/" }) }}" class="btn text-primary font-weight-bold"><i class="mdi mdi-24px mdi-star" style="color:lightgrey;"></i> stats</a></td>
        </table>
    </div>
</div>

 {% endif %}

templates/repo/fragments/header_js.html.twig
<script src="/js/jquery.timeago.js" type="text/javascript"></script>

<script>
    $(document).ready(function() {
        jQuery("time.timeago").timeago();
    });

    $(document).ready(function() {
       $('#branch_submit').click(function (e) {
           window.location = $('#branch_select option:selected').data('href');
           e.preventDefault();
       });

        $('#tag_submit').click(function (e) {
            window.location = $('#tag_select option:selected').data('href');
            e.preventDefault();
        });

    });
</script>